#!/bin/bash
# post_bootstrap.sh - Patroni post-bootstrap script
#
# Runs ONCE after PostgreSQL initialization on the primary node.
# Patroni 4.0+ removed bootstrap.users, so users must be created here.
#
# Patroni passes:
#   $1 = connection string URL (e.g., postgres://user@localhost:5432/postgres)
#   PGPASSFILE = path to pgpass file for authentication

set -e

echo "Post-bootstrap: starting..."

# Connection URL passed by Patroni (includes superuser credentials)
CONN_URL="${1:-}"

echo "DEBUG: Connection URL provided: ${CONN_URL:+yes}"
echo "DEBUG: PGPASSFILE=${PGPASSFILE:-not set}"

# Read credentials from the Patroni config file
# This is generated by patroni-runner.sh before starting Patroni
PATRONI_CONFIG="/tmp/patroni.yml"

if [ ! -f "$PATRONI_CONFIG" ]; then
    echo "ERROR: Patroni config not found at $PATRONI_CONFIG"
    exit 1
fi

# Extract credentials from YAML (simple grep since yq may not be available)
# The YAML structure is:
#   authentication:
#     replication:
#       username: replicator
#       password: xxxxx
#     superuser:
#       username: postgres
#       password: xxxxx
REPL_USER=$(grep -A2 'replication:' "$PATRONI_CONFIG" | grep 'username:' | head -1 | sed 's/.*username: *//')
REPL_PASS=$(grep -A2 'replication:' "$PATRONI_CONFIG" | grep 'password:' | head -1 | sed 's/.*password: *//')

echo "DEBUG: REPL_USER=${REPL_USER}"
echo "DEBUG: REPL_PASS length=${#REPL_PASS}"

if [ -z "$REPL_USER" ] || [ -z "$REPL_PASS" ]; then
    echo "ERROR: Could not extract replication credentials from Patroni config"
    echo "Config file contents (passwords redacted):"
    sed 's/password:.*/password: [REDACTED]/' "$PATRONI_CONFIG"
    exit 1
fi

echo "Post-bootstrap: creating replication user..."

# Force Unix socket connection by explicitly specifying socket directory
# Railway sets PGHOST which would cause TCP connection - override with -h flag
# The -h /var/run/postgresql forces local socket (matches "local all all trust" in pg_hba)
psql -v ON_ERROR_STOP=1 -h /var/run/postgresql -p 5432 -U postgres -d postgres -c \
    "DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${REPL_USER}') THEN
            EXECUTE format('CREATE ROLE %I WITH REPLICATION LOGIN PASSWORD %L', '${REPL_USER}', '${REPL_PASS}');
            RAISE NOTICE 'Created replication user: ${REPL_USER}';
        ELSE
            EXECUTE format('ALTER ROLE %I WITH PASSWORD %L', '${REPL_USER}', '${REPL_PASS}');
            RAISE NOTICE 'Updated existing user: ${REPL_USER}';
        END IF;
    END
    \$\$;"

echo "Post-bootstrap: replication user created"

# Generate SSL certificates
echo "Post-bootstrap: generating SSL certificates..."
bash /docker-entrypoint-initdb.d/init-ssl.sh

# Mark bootstrap as complete
touch "${RAILWAY_VOLUME_MOUNT_PATH:-/var/lib/postgresql/data}/.patroni_bootstrap_complete"

echo "Post-bootstrap: completed successfully"
