#!/bin/bash
# post_bootstrap.sh - Patroni post-bootstrap script
#
# Runs ONCE after PostgreSQL initialization on the primary node.
# Patroni 4.0+ removed bootstrap.users, so users must be created here.
#
# Patroni passes:
#   $1 = connection string URL (e.g., postgres://user@localhost:5432/postgres)
#   PGPASSFILE = path to pgpass file for authentication

set -e

echo "Post-bootstrap: starting..."

# Connection URL passed by Patroni (includes superuser credentials)
CONN_URL="${1:-}"

echo "DEBUG: Connection URL provided: ${CONN_URL:+yes}"
echo "DEBUG: PGPASSFILE=${PGPASSFILE:-not set}"

# Read credentials from the Patroni config file
# This is generated by patroni-runner.sh before starting Patroni
PATRONI_CONFIG="/tmp/patroni.yml"

if [ ! -f "$PATRONI_CONFIG" ]; then
    echo "ERROR: Patroni config not found at $PATRONI_CONFIG"
    exit 1
fi

# Extract credentials from YAML (simple grep since yq may not be available)
# The YAML structure is:
#   authentication:
#     replication:
#       username: replicator
#       password: xxxxx
#     superuser:
#       username: postgres
#       password: xxxxx
#   app_user:
#     username: postgres
#     password: xxxxx
REPL_USER=$(grep -A2 'replication:' "$PATRONI_CONFIG" | grep 'username:' | head -1 | sed 's/.*username: *//')
REPL_PASS=$(grep -A2 'replication:' "$PATRONI_CONFIG" | grep 'password:' | head -1 | sed 's/.*password: *//')
SUPERUSER=$(grep -A2 'superuser:' "$PATRONI_CONFIG" | grep 'username:' | head -1 | sed 's/.*username: *//')
APP_USER=$(grep -A2 'app_user:' "$PATRONI_CONFIG" | grep 'username:' | head -1 | sed 's/.*username: *//')
APP_PASS=$(grep -A2 'app_user:' "$PATRONI_CONFIG" | grep 'password:' | head -1 | sed 's/.*password: *//')

echo "DEBUG: REPL_USER=${REPL_USER}"
echo "DEBUG: REPL_PASS length=${#REPL_PASS}"

if [ -z "$REPL_USER" ] || [ -z "$REPL_PASS" ]; then
    echo "ERROR: Could not extract replication credentials from Patroni config"
    echo "Config file contents (passwords redacted):"
    sed 's/password:.*/password: [REDACTED]/' "$PATRONI_CONFIG"
    exit 1
fi

# Extract superuser password too
SUPERUSER_PASS=$(grep -A2 'superuser:' "$PATRONI_CONFIG" | grep 'password:' | head -1 | sed 's/.*password: *//')

# Patroni passes --username to initdb, so the superuser is whatever is configured
# (e.g., 'admin' not 'postgres'). Connect as that user.
echo "Post-bootstrap: setting up users (connecting as $SUPERUSER)..."

# Use env -i to run psql with a completely clean environment
# This ensures no PG* variables can interfere with the -h flag
env -i PATH="$PATH" psql -v ON_ERROR_STOP=1 -h /var/run/postgresql -U "$SUPERUSER" -d postgres <<EOSQL
-- Set password for the superuser (already exists from initdb)
ALTER ROLE ${SUPERUSER} WITH PASSWORD '${SUPERUSER_PASS}';

-- Create or update replication user
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${REPL_USER}') THEN
        EXECUTE format('CREATE ROLE %I WITH REPLICATION LOGIN PASSWORD %L', '${REPL_USER}', '${REPL_PASS}');
        RAISE NOTICE 'Created replication user: ${REPL_USER}';
    ELSE
        EXECUTE format('ALTER ROLE %I WITH PASSWORD %L', '${REPL_USER}', '${REPL_PASS}');
        RAISE NOTICE 'Updated replication user: ${REPL_USER}';
    END IF;
END
\$\$;

-- Create or update app user (POSTGRES_USER) if different from superuser
DO \$\$
BEGIN
    -- Skip if app_user is same as superuser (already handled above)
    IF '${APP_USER}' = '${SUPERUSER}' THEN
        RAISE NOTICE 'App user same as superuser, skipping';
    ELSIF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${APP_USER}') THEN
        EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L', '${APP_USER}', '${APP_PASS}');
        RAISE NOTICE 'Created app user: ${APP_USER}';
    ELSE
        EXECUTE format('ALTER ROLE %I WITH PASSWORD %L', '${APP_USER}', '${APP_PASS}');
        RAISE NOTICE 'Updated app user: ${APP_USER}';
    END IF;
END
\$\$;
EOSQL

echo "Post-bootstrap: users created (superuser: ${SUPERUSER}, replication: ${REPL_USER}, app: ${APP_USER})"

# Generate SSL certificates
echo "Post-bootstrap: generating SSL certificates..."
bash /docker-entrypoint-initdb.d/init-ssl.sh

# Mark bootstrap as complete
touch "${RAILWAY_VOLUME_MOUNT_PATH:-/var/lib/postgresql/data}/.patroni_bootstrap_complete"

echo "Post-bootstrap: completed successfully"
